In [1]:
import pandas as pd
import numpy as np

## Extracting features of 2022 movies from Wikipedia

In [10]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2022"
df1 = pd.read_html(link, header=0)[2]
df2 = pd.read_html(link, header=0)[3]
df3 = pd.read_html(link, header=0)[4]
df4 = pd.read_html(link, header=0)[5]

In [11]:
# this two rows are going to coz further error coz tmbd doesn't have movie having this title
# you can also auttomate this process by modifying the function if present in huge number
df2['Title'][4] = 'Apollo 10½: A Space Age Childhood'

C:\Users\amulya shetty\AppData\Local\Temp\ipykernel_18472\864012643.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Title'][4] = 'Apollo 10½: A Space Age Childhood'

In [12]:
#combining all quaters
df = pd.concat([df1,pd.concat([df2,pd.concat([df3,df4],ignore_index=True)],ignore_index=True)], ignore_index=True)

In [13]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.
0,J A N U A R Y,7.0,The 355,Universal Pictures / Freckle Films / FilmNatio...,Simon Kinberg (director/screenplay); Theresa R...,[2]
1,J A N U A R Y,7.0,The Legend of La Llorona,Saban Films / Ageless Pictures,Patricia Harris Seeley (director); José Prende...,[3]
2,J A N U A R Y,7.0,The Commando,Saban Films / Premiere Entertainment,Asif Akbar (director); Koji Steven Sakai (scre...,[4]
3,J A N U A R Y,7.0,American Siege,Vertical Entertainment,Edward John Drake (director/screenplay); Timot...,[5]
4,J A N U A R Y,14.0,Scream,Paramount Pictures / Spyglass Media Group / Ra...,"Matt Bettinelli-Olpin, Tyler Gillett (director...",[6]
...,...,...,...,...,...,...
311,D E C E M B E R,30.0,"Alice, Darling",Lionsgate / Elevation Pictures,Mary Nighy (director); Alanna Francis (screenp...,[259]
312,D E C E M B E R,NaN,NaN,NaN,NaN,NaN
313,D E C E M B E R,NaN,NaN,NaN,NaN,NaN
314,D E C E M B E R,NaN,NaN,NaN,NaN,NaN
315,D E C E M B E R,NaN,NaN,NaN,NaN,NaN

In [14]:
from tmdbv3api import TMDb
import requests
tmdb = TMDb()
tmdb.api_key = '61eba94e833683f5a5dad5a53c3c9c4a' #your api key will be here

In [15]:
from tmdbv3api import Movie
tmdb_movie = Movie()
def get_genre(x):
    genres = []
    result = tmdb_movie.search(x)
    movie_id = result[0].id
    response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id,tmdb.api_key))
    data_json = response.json()
    if data_json['genres']:
        genre_str = " " 
        for i in range(0,len(data_json['genres'])):
            genres.append(data_json['genres'][i]['name'])
        return genre_str.join(genres)
    else:
        np.NaN

In [16]:
df['genres'] = df['Title'].map(lambda x: get_genre(str(x)))

In [17]:
df.head()

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.,genres
0,J A N U A R Y,7.0,The 355,Universal Pictures / Freckle Films / FilmNatio...,Simon Kinberg (director/screenplay); Theresa R...,[2],Action Thriller
1,J A N U A R Y,7.0,The Legend of La Llorona,Saban Films / Ageless Pictures,Patricia Harris Seeley (director); José Prende...,[3],Family Animation Fantasy Horror
2,J A N U A R Y,7.0,The Commando,Saban Films / Premiere Entertainment,Asif Akbar (director); Koji Steven Sakai (scre...,[4],Action Crime Thriller
3,J A N U A R Y,7.0,American Siege,Vertical Entertainment,Edward John Drake (director/screenplay); Timot...,[5],Action Adventure Thriller
4,J A N U A R Y,14.0,Scream,Paramount Pictures / Spyglass Media Group / Ra...,"Matt Bettinelli-Olpin, Tyler Gillett (director...",[6],Crime Horror Mystery

In [18]:
df_2022 = df[['Title','Cast and crew','genres']]

In [19]:
def get_director(x):
    if " (director)" in x:
        return x.split(" (director)")[0]
    elif " (directors)" in x:
        return x.split(" (directors)")[0]
    else:
        return x.split(" (director/screenplay)")[0]

In [20]:
def get_director(x):
    if " (director)" in x:
        return x.split(" (director)")[0]
    elif " (directors)" in x:
        return x.split(" (directors)")[0]
    else:
        return x.split(" (director/screenplay)")[0]

In [28]:
df_2022['director_name'] = df_2022['Cast and crew'].map(lambda x: get_director(str(x)))

C:\Users\amulya shetty\AppData\Local\Temp\ipykernel_18472\3796821595.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2022['director_name'] = df_2022['Cast and crew'].map(lambda x: get_director(str(x)))

In [29]:
df_2022.head()

,Title,Cast and crew,genres,director_name
0,The 355,Simon Kinberg (director/screenplay); Theresa R...,Action Thriller,Simon Kinberg
1,The Legend of La Llorona,Patricia Harris Seeley (director); José Prende...,Family Animation Fantasy Horror,Patricia Harris Seeley
2,The Commando,Asif Akbar (director); Koji Steven Sakai (scre...,Action Crime Thriller,Asif Akbar
3,American Siege,Edward John Drake (director/screenplay); Timot...,Action Adventure Thriller,Edward John Drake
4,Scream,"Matt Bettinelli-Olpin, Tyler Gillett (director...",Crime Horror Mystery,"Matt Bettinelli-Olpin, Tyler Gillett"

In [31]:
def get_actor1(x):
    return (x.split('screenplay); ')[-1].split(', ')[0])

In [32]:
df_2022['actor_1_name'] = df_2022['Cast and crew'].map(lambda x : get_actor1(str(x)))

C:\Users\amulya shetty\AppData\Local\Temp\ipykernel_18472\199187862.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2022['actor_1_name'] = df_2022['Cast and crew'].map(lambda x : get_actor1(str(x)))

In [33]:
def get_actor2(x):
    if len((x.split('screenplay); ')[-1]).split(', ')) < 2:
        return np.NAN
    else :
        return (x.split('screenplay); ')[-1].split(', ')[1])

In [34]:
df_2022['actor_2_name'] = df_2022['Cast and crew'].map(lambda x: get_actor2(str(x)))

C:\Users\amulya shetty\AppData\Local\Temp\ipykernel_18472\2384233428.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2022['actor_2_name'] = df_2022['Cast and crew'].map(lambda x: get_actor2(str(x)))

In [35]:
def get_actor3(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 3:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[2])

In [36]:
df_2022['actor_3_name'] = df_2022['Cast and crew'].map(lambda x: get_actor3(str(x)))

In [37]:
df_2022.head()

,Title,Cast and crew,genres,director_name,actor_1_name,actor_2_name,actor_3_name
0,The 355,Simon Kinberg (director/screenplay); Theresa R...,Action Thriller,Simon Kinberg,Jessica Chastain,Penélope Cruz,Fan Bingbing
1,The Legend of La Llorona,Patricia Harris Seeley (director); José Prende...,Family Animation Fantasy Horror,Patricia Harris Seeley,Autumn Reeser,Danny Trejo,Antonio Cupo
2,The Commando,Asif Akbar (director); Koji Steven Sakai (scre...,Action Crime Thriller,Asif Akbar,Mickey Rourke,Michael Jai White,NaN
3,American Siege,Edward John Drake (director/screenplay); Timot...,Action Adventure Thriller,Edward John Drake,Timothy V. Murphy,Bruce Willis,Rob Gough
4,Scream,"Matt Bettinelli-Olpin, Tyler Gillett (director...",Crime Horror Mystery,"Matt Bettinelli-Olpin, Tyler Gillett",Melissa Barrera,Mason Gooding,Jenna Ortega

In [38]:
df_2022 = df_2022.rename(columns={'Title':'movie_title'})

In [39]:
new_df22 = df_2022.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [40]:
new_df22.isna().sum()

director_name     0
actor_1_name      0
actor_2_name     12
actor_3_name     36
genres            0
movie_title       4
dtype: int64

In [45]:
new_df22['actor_2_name'] = new_df22['actor_2_name'].replace(np.nan, 'unknown')
new_df22['actor_3_name'] = new_df22['actor_3_name'].replace(np.nan, 'unknown')
new_df22.dropna(inplace=True)

In [46]:
new_df22.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
movie_title      0
comb             0
dtype: int64

In [47]:
new_df22['movie_title'] = new_df22['movie_title'].str.lower()

In [48]:
new_df22['comb'] = new_df22['actor_1_name'] + ' ' + new_df22['actor_2_name'] + ' '+ new_df22['actor_3_name'] + ' '+ new_df22['director_name'] +' ' + new_df22['genres']

In [49]:
new_df22

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Simon Kinberg,Jessica Chastain,Penélope Cruz,Fan Bingbing,Action Thriller,the 355,Jessica Chastain Penélope Cruz Fan Bingbing Si...
1,Patricia Harris Seeley,Autumn Reeser,Danny Trejo,Antonio Cupo,Family Animation Fantasy Horror,the legend of la llorona,Autumn Reeser Danny Trejo Antonio Cupo Patrici...
2,Asif Akbar,Mickey Rourke,Michael Jai White,unknown,Action Crime Thriller,the commando,Mickey Rourke Michael Jai White unknown Asif A...
3,Edward John Drake,Timothy V. Murphy,Bruce Willis,Rob Gough,Action Adventure Thriller,american siege,Timothy V. Murphy Bruce Willis Rob Gough Edwar...
4,"Matt Bettinelli-Olpin, Tyler Gillett",Melissa Barrera,Mason Gooding,Jenna Ortega,Crime Horror Mystery,scream,Melissa Barrera Mason Gooding Jenna Ortega Mat...
...,...,...,...,...,...,...,...
307,Kasi Lemmons,Naomi Ackie,Stanley Tucci,Ashton Sanders,Music History Drama,whitney houston: i wanna dance with somebody,Naomi Ackie Stanley Tucci Ashton Sanders Kasi ...
308,Scott Cooper,Christian Bale,Harry Melling,Gillian Anderson,Thriller Crime Horror Mystery,the pale blue eye,Christian Bale Harry Melling Gillian Anderson ...
309,Sarah Polley,Rooney Mara,Claire Foy,Jessie Buckley,Drama Crime,women talking,Rooney Mara Claire Foy Jessie Buckley Sarah Po...
310,Marc Forster,Tom Hanks,Mariana Treviño,Rachel Keller,Comedy Drama,a man called otto,Tom Hanks Mariana Treviño Rachel Keller Marc F...
311,Mary Nighy,Anna Kendrick,Kaniehtiio Horn,Charlie Carrick,Thriller Drama,"alice, darling",Anna Kendrick Kaniehtiio Horn Charlie Carrick ...

## Extracting features of 2023 movies from Wikipedia

In [52]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2023"
df1 = pd.read_html(link, header=0)[2]
df2 = pd.read_html(link, header=0)[3]
df3 = pd.read_html(link, header=0)[4]
df4 = pd.read_html(link, header=0)[5]

In [ ]:
df3.drop(index=87,inplace= True)

In [53]:
df = pd.concat([df1,pd.concat([df2,pd.concat([df3,df4],ignore_index=True)],ignore_index=True)],ignore_index=True)

In [54]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.
0,J A N U A R Y,6,M3GAN,Universal Pictures / Blumhouse Productions / A...,Gerard Johnstone (director); Akela Cooper (scr...,[3]
1,J A N U A R Y,6,The Old Way,Saban Films / Saturn Films,Brett Donowho (director); Carl W. Lucas (scree...,[4]
2,J A N U A R Y,11,The Devil Conspiracy,Samuel Goldwyn Films,Nathan Frankowski (director); Ed Alan (screenp...,[5]
3,J A N U A R Y,13,Plane,Lionsgate / MadRiver Pictures / Di Bonaventura...,Jean-François Richet (director); Charles Cummi...,[6]
4,J A N U A R Y,13,House Party,Warner Bros. Pictures / New Line Cinema,"Calmatic (director); Jamal Olori, Stephen Glov...",[7]
...,...,...,...,...,...,...
332,D E C E M B E R,22,Memory,Ketchup Entertainment / Mubi,Michel Franco (director/screenplay); Jessica C...,[319]
333,D E C E M B E R,25,The Color Purple,Warner Bros. Pictures / Amblin Entertainment /...,"Blitz Bazawule (director), Marcus Gardley (scr...",[320]
334,D E C E M B E R,25,The Boys in the Boat,Metro-Goldwyn-Mayer / Smokehouse Pictures,"George Clooney (director), Mark L. Smith (scre...",[321]
335,D E C E M B E R,25,Ferrari,Neon / STXfilms / Ketchup Entertainment,"Michael Mann (director), Troy Kennedy Martin (...",[322]
336,D E C E M B E R,29,Good Grief,Netflix,"Dan Levy (director/screenplay); Dan Levy, Ruth...",[323]

In [56]:
df['genres'] = df['Title'].map(lambda x : get_genre(str(x)))

In [57]:
df_2023 = df[['Title','Cast and crew','genres']]

In [58]:
df_2023.head()

,Title,Cast and crew,genres
0,M3GAN,Gerard Johnstone (director); Akela Cooper (scr...,Science Fiction Horror
1,The Old Way,Brett Donowho (director); Carl W. Lucas (scree...,Western Drama
2,The Devil Conspiracy,Nathan Frankowski (director); Ed Alan (screenp...,Horror Fantasy Science Fiction Thriller
3,Plane,Jean-François Richet (director); Charles Cummi...,Action
4,House Party,"Calmatic (director); Jamal Olori, Stephen Glov...",Comedy

In [59]:
df_2023['director_name'] = df_2023['Cast and crew'].map(lambda x : get_director(str(x)))

C:\Users\amulya shetty\AppData\Local\Temp\ipykernel_18472\2908961938.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023['director_name'] = df_2023['Cast and crew'].map(lambda x : get_director(str(x)))

In [60]:
df_2023['actor_1_name'] = df_2023['Cast and crew'].map(lambda x: get_actor1(str(x)))

C:\Users\amulya shetty\AppData\Local\Temp\ipykernel_18472\4038699429.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023['actor_1_name'] = df_2023['Cast and crew'].map(lambda x: get_actor1(str(x)))

In [61]:
df_2023['actor_2_name'] = df_2023['Cast and crew'].map(lambda x: get_actor2(str(x)))

C:\Users\amulya shetty\AppData\Local\Temp\ipykernel_18472\829297059.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023['actor_2_name'] = df_2023['Cast and crew'].map(lambda x: get_actor2(str(x)))

In [62]:
df_2023['actor_3_name'] = df_2023['Cast and crew'].map(lambda x: get_actor3(str(x)))

In [63]:
df_2023 = df_2023.rename(columns={'Title':'movie_title'})

In [64]:
new_df23 = df_2023.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [65]:
new_df23.isna().sum()

director_name     0
actor_1_name      0
actor_2_name      3
actor_3_name     21
genres            0
movie_title       0
dtype: int64

In [66]:
new_df23['actor_2_name'] = new_df23['actor_2_name'].replace(np.nan, 'unknown')
new_df23['actor_3_name'] = new_df23['actor_3_name'].replace(np.nan, 'unknown')
new_df23.dropna(inplace=True)

In [67]:
new_df23.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
movie_title      0
dtype: int64

In [68]:
new_df23['movie_title'] = new_df23['movie_title'].str.lower()

In [69]:
new_df23['comb'] = new_df23['actor_1_name'] + ' ' + new_df23['actor_2_name'] + ' '+ new_df23['actor_3_name'] + ' '+ new_df23['director_name'] +' ' + new_df23['genres']

In [70]:
new_df23

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Gerard Johnstone,Allison Williams,Violet McGraw,Amie Donald,Science Fiction Horror,m3gan,Allison Williams Violet McGraw Amie Donald Ger...
1,Brett Donowho,Nicolas Cage,Ryan Kiera Armstrong,unknown,Western Drama,the old way,Nicolas Cage Ryan Kiera Armstrong unknown Bret...
2,Nathan Frankowski,Alice Orr-Ewing,Joe Doyle,Eveline Hall,Horror Fantasy Science Fiction Thriller,the devil conspiracy,Alice Orr-Ewing Joe Doyle Eveline Hall Nathan ...
3,Jean-François Richet,Gerard Butler,Mike Colter,Yoson An,Action,plane,Gerard Butler Mike Colter Yoson An Jean-Franço...
4,Calmatic,Tosin Cole,Jacob Latimore,Karen Obilom,Comedy,house party,Tosin Cole Jacob Latimore Karen Obilom Calmati...
...,...,...,...,...,...,...,...
332,Michel Franco,Jessica Chastain,Peter Sarsgaard,Merritt Wever,Action Thriller Crime,memory,Jessica Chastain Peter Sarsgaard Merritt Wever...
333,Blitz Bazawule,Fantasia Barrino,Taraji P. Henson,Danielle Brooks,Music Drama,the color purple,Fantasia Barrino Taraji P. Henson Danielle Bro...
334,George Clooney,Callum Turner,Joel Edgerton,Peter Guinness,Drama History,the boys in the boat,Callum Turner Joel Edgerton Peter Guinness Geo...
335,Michael Mann,Adam Driver,Penelope Cruz,Shailene Woodley,Drama History,ferrari,Adam Driver Penelope Cruz Shailene Woodley Mic...
336,Dan Levy,Dan Levy,Ruth Negga,Himesh Patel,Comedy Drama Romance,good grief,Dan Levy Ruth Negga Himesh Patel Dan Levy Come...

In [71]:
my_df = pd.concat([new_df22,new_df23], ignore_index=True)

In [72]:
my_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Simon Kinberg,Jessica Chastain,Penélope Cruz,Fan Bingbing,Action Thriller,the 355,Jessica Chastain Penélope Cruz Fan Bingbing Si...
1,Patricia Harris Seeley,Autumn Reeser,Danny Trejo,Antonio Cupo,Family Animation Fantasy Horror,the legend of la llorona,Autumn Reeser Danny Trejo Antonio Cupo Patrici...
2,Asif Akbar,Mickey Rourke,Michael Jai White,unknown,Action Crime Thriller,the commando,Mickey Rourke Michael Jai White unknown Asif A...
3,Edward John Drake,Timothy V. Murphy,Bruce Willis,Rob Gough,Action Adventure Thriller,american siege,Timothy V. Murphy Bruce Willis Rob Gough Edwar...
4,"Matt Bettinelli-Olpin, Tyler Gillett",Melissa Barrera,Mason Gooding,Jenna Ortega,Crime Horror Mystery,scream,Melissa Barrera Mason Gooding Jenna Ortega Mat...
...,...,...,...,...,...,...,...
644,Michel Franco,Jessica Chastain,Peter Sarsgaard,Merritt Wever,Action Thriller Crime,memory,Jessica Chastain Peter Sarsgaard Merritt Wever...
645,Blitz Bazawule,Fantasia Barrino,Taraji P. Henson,Danielle Brooks,Music Drama,the color purple,Fantasia Barrino Taraji P. Henson Danielle Bro...
646,George Clooney,Callum Turner,Joel Edgerton,Peter Guinness,Drama History,the boys in the boat,Callum Turner Joel Edgerton Peter Guinness Geo...
647,Michael Mann,Adam Driver,Penelope Cruz,Shailene Woodley,Drama History,ferrari,Adam Driver Penelope Cruz Shailene Woodley Mic...
648,Dan Levy,Dan Levy,Ruth Negga,Himesh Patel,Comedy Drama Romance,good grief,Dan Levy Ruth Negga Himesh Patel Dan Levy Come...

In [73]:
old_df = pd.read_csv('../datasets/grandfinal_data.csv')

In [74]:
old_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action|Adventure|Fantasy|Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action|Adventure|Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action|Adventure|Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action|Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakens ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
6452,Matthew Vaughn,Ralph Fiennes,Gemma Arterton,Rhys Ifans,Action Comedy Adventure Thriller,the king's man,Ralph Fiennes Gemma Arterton Rhys Ifans Matthe...
6453,Joel Coen,Denzel Washington,Frances McDormand,Bertie Carvel,Drama War,the tragedy of macbeth,Denzel Washington Frances McDormand Bertie Car...
6454,Denzel Washington,Michael B. Jordan,Chanté Adams,Jalon Christian,Drama Romance,a journal for jordan,Michael B. Jordan Chanté Adams Jalon Christian...
6455,Erwin brothers,Zachary Levi,Anna Paquin,Dennis Quaid,Drama,american underdog,Zachary Levi Anna Paquin Dennis Quaid Erwin br...
6456,Apichatpong Weerasethakul (director/acreenplay...,Apichatpong Weerasethakul (director/acreenplay...,Elkin Díaz,Jeanne Balibar,Drama Science Fiction Mystery,memoria,Apichatpong Weerasethakul (director/acreenplay...

In [75]:
final_df = pd.concat([old_df,my_df],ignore_index=True)

In [76]:
final_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action|Adventure|Fantasy|Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action|Adventure|Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action|Adventure|Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action|Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakens ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
7101,Michel Franco,Jessica Chastain,Peter Sarsgaard,Merritt Wever,Action Thriller Crime,memory,Jessica Chastain Peter Sarsgaard Merritt Wever...
7102,Blitz Bazawule,Fantasia Barrino,Taraji P. Henson,Danielle Brooks,Music Drama,the color purple,Fantasia Barrino Taraji P. Henson Danielle Bro...
7103,George Clooney,Callum Turner,Joel Edgerton,Peter Guinness,Drama History,the boys in the boat,Callum Turner Joel Edgerton Peter Guinness Geo...
7104,Michael Mann,Adam Driver,Penelope Cruz,Shailene Woodley,Drama History,ferrari,Adam Driver Penelope Cruz Shailene Woodley Mic...
7105,Dan Levy,Dan Levy,Ruth Negga,Himesh Patel,Comedy Drama Romance,good grief,Dan Levy Ruth Negga Himesh Patel Dan Levy Come...

In [77]:
final_df.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
movie_title      0
comb             0
dtype: int64

In [78]:
final_df.duplicated().sum()

0

In [79]:
final_df.drop_duplicates(subset ="movie_title", keep = 'last', inplace = True)

In [80]:
final_df.duplicated().sum()

0

In [81]:
final_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action|Adventure|Fantasy|Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action|Adventure|Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action|Adventure|Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action|Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakens ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
7101,Michel Franco,Jessica Chastain,Peter Sarsgaard,Merritt Wever,Action Thriller Crime,memory,Jessica Chastain Peter Sarsgaard Merritt Wever...
7102,Blitz Bazawule,Fantasia Barrino,Taraji P. Henson,Danielle Brooks,Music Drama,the color purple,Fantasia Barrino Taraji P. Henson Danielle Bro...
7103,George Clooney,Callum Turner,Joel Edgerton,Peter Guinness,Drama History,the boys in the boat,Callum Turner Joel Edgerton Peter Guinness Geo...
7104,Michael Mann,Adam Driver,Penelope Cruz,Shailene Woodley,Drama History,ferrari,Adam Driver Penelope Cruz Shailene Woodley Mic...
7105,Dan Levy,Dan Levy,Ruth Negga,Himesh Patel,Comedy Drama Romance,good grief,Dan Levy Ruth Negga Himesh Patel Dan Levy Come...

## Extracting features of 2024 movies from Wikipedia

In [82]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2024"
df1 = pd.read_html(link, header=0)[2]
df2 = pd.read_html(link, header=0)[3]
df3 = pd.read_html(link, header=0)[4]
df4 = pd.read_html(link, header=0)[5]

In [86]:
df4.drop(index=3,inplace=True)
df4.drop(index=15,inplace=True)

In [87]:
df = pd.concat([df1,pd.concat([df2,pd.concat([df3,df4],ignore_index=True)],ignore_index=True)],ignore_index=True)

In [88]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.
0,J A N U A R Y,2,The Mummy Murders,Gravitas Ventures,Colin Bressler (director/screenplay); Will Don...,[3]
1,J A N U A R Y,3,Self Reliance,Neon / Hulu / MRC / Paramount Global Content D...,Jake Johnson (director/screenplay); Jake Johns...,[4]
2,J A N U A R Y,4,DarkGame,Gravitas Ventures,"Howard J. Ford (director); Gary Grant, Niall J...",[5]
3,J A N U A R Y,5,Night Swim,Universal Pictures / Blumhouse Productions / A...,Bryce McGuire (director/screenplay); Wyatt Rus...,[6]
4,J A N U A R Y,5,He Went That Way,Vertical Entertainment / Mister Smith Entertai...,Jeffrey Darling (director); Evan M. Wiener (sc...,[7]
...,...,...,...,...,...,...
177,N O V E M B E R,27,Wicked,Universal Pictures / Marc Platt Productions,"Jon M. Chu (director); Stephen Schwartz, Winni...",[165]
178,D E C E M B E R,13,The Lord of the Rings: The War of the Rohirrim,Warner Bros. Pictures / New Line Cinema / Sola...,"Kenji Kamiyama (director); Phoebe Gittins, Art...",[166]
179,D E C E M B E R,20,Sonic the Hedgehog 3,Paramount Pictures / Sega Sammy Group / Origin...,"Jeff Fowler (director); Patrick Casey, Josh Mi...",[167]
180,D E C E M B E R,20,Mufasa: The Lion King,Walt Disney Pictures / Pastel Productions,Barry Jenkins (director); Jeff Nathanson (scre...,[141]
181,D E C E M B E R,25,Nosferatu,Focus Features / Studio 8,Robert Eggers (director/screenplay); Bill Skar...,[168]

In [89]:
df['genres'] = df['Title'].map(lambda x : get_genre(str(x)))

In [90]:
df_2024 = df[['Title','Cast and crew','genres']]

In [91]:
df_2024.head()

,Title,Cast and crew,genres
0,The Mummy Murders,Colin Bressler (director/screenplay); Will Don...,Horror Crime
1,Self Reliance,Jake Johnson (director/screenplay); Jake Johns...,Comedy Thriller
2,DarkGame,"Howard J. Ford (director); Gary Grant, Niall J...",Horror Thriller
3,Night Swim,Bryce McGuire (director/screenplay); Wyatt Rus...,Horror
4,He Went That Way,Jeffrey Darling (director); Evan M. Wiener (sc...,Mystery Thriller Crime Drama

In [92]:
df_2024['director_name'] = df_2024['Cast and crew'].map(lambda x : get_director(str(x)))

C:\Users\amulya shetty\AppData\Local\Temp\ipykernel_18472\2073821017.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2024['director_name'] = df_2024['Cast and crew'].map(lambda x : get_director(str(x)))

In [93]:
df_2024['actor_1_name'] = df_2024['Cast and crew'].map(lambda x: get_actor1(str(x)))

C:\Users\amulya shetty\AppData\Local\Temp\ipykernel_18472\1172275945.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2024['actor_1_name'] = df_2024['Cast and crew'].map(lambda x: get_actor1(str(x)))

In [94]:
df_2024['actor_2_name'] = df_2024['Cast and crew'].map(lambda x: get_actor2(str(x)))

C:\Users\amulya shetty\AppData\Local\Temp\ipykernel_18472\1503802944.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2024['actor_2_name'] = df_2024['Cast and crew'].map(lambda x: get_actor2(str(x)))

In [95]:
df_2024['actor_3_name'] = df_2024['Cast and crew'].map(lambda x: get_actor3(str(x)))

In [96]:
df_2024 = df_2024.rename(columns={'Title':'movie_title'})

In [97]:
new_df24 = df_2024.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [98]:
new_df24.isna().sum()

director_name     0
actor_1_name      0
actor_2_name      3
actor_3_name     13
genres            2
movie_title       0
dtype: int64

In [100]:
new_df24['actor_2_name'] = new_df24['actor_2_name'].replace(np.nan, 'unknown')
new_df24['actor_3_name'] = new_df24['actor_3_name'].replace(np.nan, 'unknown')
new_df24.dropna(inplace=True)

In [101]:
new_df24.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
movie_title      0
dtype: int64

In [102]:
new_df24['movie_title'] = new_df24['movie_title'].str.lower()

In [111]:
new_df24['comb'] = new_df24['actor_1_name'] + ' ' + new_df24['actor_2_name'] + ' '+ new_df24['actor_3_name'] + ' '+ new_df24['director_name'] +' ' + new_df24['genres']

In [112]:
new_df24

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Colin Bressler,Leila Annastasia Scott,Jason Scarbrough,Jeff Caperton,Horror Crime,the mummy murders,Leila Annastasia Scott Jason Scarbrough Jeff C...
1,Jake Johnson,Jake Johnson,Anna Kendrick,Natalie Morales,Comedy Thriller,self reliance,Jake Johnson Anna Kendrick Natalie Morales Jak...
2,Howard J. Ford,Ed Westwick,Andrew P. Stephen,Natalya Tsvetkova,Horror Thriller,darkgame,Ed Westwick Andrew P. Stephen Natalya Tsvetkov...
3,Bryce McGuire,Wyatt Russell,Kerry Condon,Amélie Hoeferle,Horror,night swim,Wyatt Russell Kerry Condon Amélie Hoeferle Bry...
4,Jeffrey Darling,Jacob Elordi,Zachary Quinto,Patrick J. Adams,Mystery Thriller Crime Drama,he went that way,Jacob Elordi Zachary Quinto Patrick J. Adams J...
...,...,...,...,...,...,...,...
177,Jon M. Chu,Cynthia Erivo,Ariana Grande,Michelle Yeoh,Fantasy Romance Drama,wicked,Cynthia Erivo Ariana Grande Michelle Yeoh Jon ...
178,Kenji Kamiyama,Brian Cox,Miranda Otto,unknown,Animation Fantasy Action,the lord of the rings: the war of the rohirrim,Brian Cox Miranda Otto unknown Kenji Kamiyama ...
179,Jeff Fowler,James Marsden,Ben Schwartz,Tika Sumpter,Science Fiction Action Adventure Comedy,sonic the hedgehog 3,James Marsden Ben Schwartz Tika Sumpter Jeff F...
180,Barry Jenkins,Aaron Pierre,Kelvin Harrison Jr.,Seth Rogen,Adventure Animation Family,mufasa: the lion king,Aaron Pierre Kelvin Harrison Jr. Seth Rogen Ba...
181,Robert Eggers,Bill Skarsgård,Nicholas Hoult,Lily-Rose Depp,Drama Fantasy Horror,nosferatu,Bill Skarsgård Nicholas Hoult Lily-Rose Depp R...

In [113]:
my_df1 = pd.concat([final_df,new_df24], ignore_index=True)

In [114]:
my_df1

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action|Adventure|Fantasy|Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action|Adventure|Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action|Adventure|Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action|Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakens ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
7259,Jon M. Chu,Cynthia Erivo,Ariana Grande,Michelle Yeoh,Fantasy Romance Drama,wicked,Cynthia Erivo Ariana Grande Michelle Yeoh Jon ...
7260,Kenji Kamiyama,Brian Cox,Miranda Otto,unknown,Animation Fantasy Action,the lord of the rings: the war of the rohirrim,Brian Cox Miranda Otto unknown Kenji Kamiyama ...
7261,Jeff Fowler,James Marsden,Ben Schwartz,Tika Sumpter,Science Fiction Action Adventure Comedy,sonic the hedgehog 3,James Marsden Ben Schwartz Tika Sumpter Jeff F...
7262,Barry Jenkins,Aaron Pierre,Kelvin Harrison Jr.,Seth Rogen,Adventure Animation Family,mufasa: the lion king,Aaron Pierre Kelvin Harrison Jr. Seth Rogen Ba...
7263,Robert Eggers,Bill Skarsgård,Nicholas Hoult,Lily-Rose Depp,Drama Fantasy Horror,nosferatu,Bill Skarsgård Nicholas Hoult Lily-Rose Depp R...

In [115]:
my_df1.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
movie_title      0
comb             0
dtype: int64

In [116]:
my_df1.duplicated().sum()

0

In [117]:
my_df1

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action|Adventure|Fantasy|Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action|Adventure|Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action|Adventure|Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action|Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakens ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
7259,Jon M. Chu,Cynthia Erivo,Ariana Grande,Michelle Yeoh,Fantasy Romance Drama,wicked,Cynthia Erivo Ariana Grande Michelle Yeoh Jon ...
7260,Kenji Kamiyama,Brian Cox,Miranda Otto,unknown,Animation Fantasy Action,the lord of the rings: the war of the rohirrim,Brian Cox Miranda Otto unknown Kenji Kamiyama ...
7261,Jeff Fowler,James Marsden,Ben Schwartz,Tika Sumpter,Science Fiction Action Adventure Comedy,sonic the hedgehog 3,James Marsden Ben Schwartz Tika Sumpter Jeff F...
7262,Barry Jenkins,Aaron Pierre,Kelvin Harrison Jr.,Seth Rogen,Adventure Animation Family,mufasa: the lion king,Aaron Pierre Kelvin Harrison Jr. Seth Rogen Ba...
7263,Robert Eggers,Bill Skarsgård,Nicholas Hoult,Lily-Rose Depp,Drama Fantasy Horror,nosferatu,Bill Skarsgård Nicholas Hoult Lily-Rose Depp R...

In [118]:
my_df1.to_csv('../datasets/main_data.csv',index=False)